POST http://localhost:8080/projects
Content-Type: application/json

{
    "name": "3rd Sample Project",
    "description": "3rd Sample Project Description",
    "location": "3rd Sample Project Location"
}