POST http://localhost:8080/projects
Content-Type: application/json

{
    "name": "8th Sample Project",
    "description": "8th Sample Project Description",
    "location": "8th Sample Project Location"
}