PUT http://localhost:8080/projects/8
Content-Type: application/json

{
    "name": "Updated 8th Project",
    "description": "Updated 8th Project Description",
    "location": "Updated 8th Project Location"
}